In [1]:
import pandas as pd
import numpy as np

In [4]:
fn = "./t.csv"
df = pd.read_csv(fn)

In [22]:
last_position = np.array([np.nan] *13 *2 ).reshape(13,2)
# last_position.reshape(13,2)
last_position

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan]])

In [25]:
for frame in range(len(df)):
    npa = df.iloc[frame].values.reshape(13, 2)
    print(npa[~np.isnan(npa)].reshape(-1,2))


[[1535. 1023.]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[1353. 1225.]]
[]
[[1353. 1220.]]
[[1353. 1221.]
 [1565. 1026.]]
[[1353. 1220.]
 [1413.  880.]]
[[1567. 1024.]
 [1414.  880.]]
[[1355. 1217.]
 [1569. 1023.]
 [1374.  868.]]
[[1354. 1216.]
 [1570. 1024.]]
[[1353. 1215.]
 [1571. 1022.]
 [1408.  879.]
 [1494.  721.]]
[[1353. 1216.]
 [1575. 1021.]
 [1408.  879.]]
[[1355. 1214.]
 [1193. 1140.]
 [1407.  877.]
 [1496.  717.]]
[[1355. 1213.]
 [1193. 1140.]
 [1576. 1019.]
 [1406.  877.]
 [1373.  875.]
 [1495.  716.]]
[[1355. 1211.]
 [1577. 1018.]
 [1404.  876.]
 [1372.  876.]
 [1495.  715.]]
[[1354. 1211.]
 [ 938. 1142.]
 [1195. 1141.]
 [1578. 1018.]
 [1372.  878.]
 [1402.  875.]
 [1583.  811.]
 [1495.  713.]]
[[1354. 1210.]
 [ 940. 1142.]
 [1580. 1017.]
 [1816.  986.]
 [1373.  879.]
 [1400.  874.]
 [1584.  811.]
 [1494.  712.]]
[[1356. 1207.]
 [ 942. 1142.]
 [1582. 1016.]
 [1816.  987.]
 [1240.  931.]
 [1373.  883.]
 [1400.  874.]
 [1585.  812.]
 [1494.  710.]]
[[1356. 1206.]
 [ 